### ISSUE TITLE
Issueベース開発レビュー依頼

### ISSUE THREAD

**Issue by ryusato515** [ryusato515/anconnect#37]
### 概要
レビューお願いします。

### 実装予定の機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] パスワード変更機能
- [ ] メールアドレス変更機能
- [ ] 投稿機能
- [ ] 投稿閲覧機能
- [ ] MAPによる投稿閲覧機能
- [ ] 投稿編集機能
- [ ] 投稿削除機能
- [ ] コメント投稿機能
- [ ] コメント閲覧機能
- [ ] コメント編集機能
- [ ] いいね機能
- [ ] いいね解除機能

### 必要なページ
- [ ] トップページ
- [ ] 会員登録
- [ ] ログイン
- [ ] パスワード再設定
- [ ] 投稿一覧
- [ ] 投稿一覧（map）
- [ ] 新規投稿
- [ ] 投稿詳細
- [ ] 投稿編集
- [ ] マイページ
- [ ] お気に入り一覧
- [ ] 投稿一覧（自身の投稿）
- [ ] プロフィール編集
- [ ] メールアドレス変更
- [ ] パスワード変更
- [ ] 利用規約
- [ ] お問い合わせ
- [ ] プライバシーポリシー

**Comment by tarakish** [comment]
個人開発におけるプロジェクトマネジメントで作成したGitHubProjectをpublicに変更後、GitHubProjectのURLの提出もお願いしたいです

**Comment by ryusato515** [comment]
以下がGitHubProjectのURLです。
https://github.com/users/ryusato515/projects/3/views/1

確認の程よろしくお願いいたします。

**Comment by tarakish** [comment]
確認できました👍🏻
Issueの中身が書かれていないようなので、現時点で考えられる範囲で良いので各Issueでどのようなことを実装するのか追記していただけますか？

**Comment by ryusato515** [comment]
Issueの中身を追記しました。
確認よろしくお願いします。

**Comment by Tsuchiya2** [comment]
大まか良さそうですね。拝見した感じからストーリーポイント５を付けているissueは、あまり見通しができていないものだったり、慣れていないものかと感じました。ストーリーポイント５のissueはもう少し細かくissue化しておくと、進捗を実感しながら開発できますし、何より分かっている部分と分かっていない部分が可視化されて気持ちの麺でも負担が和らぐかと思うので３以下、理想は1,2くらいになるまで細分化しましょう。

**Comment by ryusato515** [comment]
ストーリーポイント５のissueを３以下になるように細分化しました。
確認のほどよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
