### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by ryusato515** [ryusato515/anconnect#79]
## 各種情報
サービス名　あんこねくと
サービスURL　https://anconnect.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] トップページ
- [ ] 会員登録・ログイン
  - [ ]  ゲスト：検索
  - [ ]  会員：検索・新規投稿・お気に入り
- [ ] 新規投稿
  - [ ]  お菓子名
  - [ ]  写真
  - [ ]  都道府県（選択）
  - [ ]  店名
  - [ ]  住所（Google Maps APIを用いてGoogleマップ上にマーカーを表示させる）
  - [ ]  種類（選択）
    - [ ]  材料（小倉あん・赤あん・白あん・うぐいすあん・ずんだあん・その他）
    - [ ]  製法（こしあん・つぶあん・小倉あん・つぶしあん）
  - [ ]  コメント
- [ ]  検索
  - [ ]  mapからの検索（Googleマップ上のマーカー）
  - [ ]  都道府県・種類での絞り込み
- [ ]  投稿一覧
- [ ]  投稿詳細
- [ ]  お気に入り
- [ ]  利用規約
- [ ]  お問い合わせ
- [ ]  プライバシーポリシー

## READMEレビュー時から変更した機能
- [ ] 住所の登録をオートコンプリートに変更

## サービスイメージがわかるようなスクリーンショット等
-  トップページ
[![Image from Gyazo](https://i.gyazo.com/39367b8cf2e4a1bc82a34369c65df7ce.jpg)](https://gyazo.com/39367b8cf2e4a1bc82a34369c65df7ce)

-  新規投稿
[![Image from Gyazo](https://i.gyazo.com/b6dbeb78b7eef38a52b85214adc25497.png)](https://gyazo.com/b6dbeb78b7eef38a52b85214adc25497)

-  投稿一覧
[![Image from Gyazo](https://i.gyazo.com/88d2321cae3399d17af5bcea2cbb2bfa.png)](https://gyazo.com/88d2321cae3399d17af5bcea2cbb2bfa)

-  mapからの検索（Googleマップ上のマーカー）
[![Image from Gyazo](https://i.gyazo.com/06e57799857defd4e042e43d731c7660.jpg)](https://gyazo.com/06e57799857defd4e042e43d731c7660)

-  投稿詳細
[![Image from Gyazo](https://i.gyazo.com/7ce7d6e4e84a0f43934afe8775e93e3b.png)](https://gyazo.com/7ce7d6e4e84a0f43934afe8775e93e3b)

**Comment by kenchasonakai** [comment]
LGTMです！
